#!/bin/bash

SUFFIX=$1

if [ -z "$SUFFIX" ]; then
    echo "Must provide run suffix"
    exit 1
fi

RUN=run$SUFFIX

if [ -e "$RUN" ]; then
    echo "$RUN already exists"
    exit 1
fi

ZIP=$RUN.zip

if [ -e "$ZIP" ]; then
    echo "$ZIP already exists"
    exit 1
fi

./Polyworld
mv run $RUN

./bin/CalcComplexity motion $RUN

cd scripts
./MakeRecentDirectorywithEntirePopulation.sh ../$RUN
./CalcComplexityOverRecent -C P Recent ../$RUN
cd ..

./pack_run $RUN $ZIP