#! /bin/bash
cd ~/src
svn checkout http://bct-cpp.googlecode.com/svn/trunk/ bct-cpp
export CVS_RSH=ssh
cvs -d:ext:larryy@polyworld.cvs.sf.net:/cvsroot/polyworld checkout -P polyworld

cd ~/Downloads
curl -o TextWrangler_3.1.dmg http://156.56.29.176/TextWrangler_3.1.dmg
curl -o epd-6.1-1-macosx-i386.dmg http://156.56.29.176/epd-6.1-1-macosx-i386.dmg
curl -o gsl-1.14.tar http://156.56.29.176/gsl-1.14.tar
open -W TextWrangler_3.1.dmg
open -W epd-6.1-1-macosx-i386.dmg

cd ~
curl -o .bash_aliases http://156.56.29.176/.bash_aliases
curl -o .bashrc http://156.56.29.176/.bashrc
curl -o .bash_profile http://156.56.29.176/.bash_profile
curl -o .setup http://156.56.29.176/.setup
curl -o .banner http://156.56.29.176/.banner
curl -o .cvsrc http://156.56.29.176/.cvsrc
curl -o .vimrc http://156.56.29.176/.vimrc

cd ~/Downloads
gnutar -xf gsl-1.14.tar
mv gsl-1.14 ../src/

cp -R "/Volumes/TextWrangler 3.1/TextWrangler.app" /Applications/
umount "/Volumes/TextWrangler 3.1"

cp ~/.bash_profile ~/.bash_profile.bak
sudo installer -pkg /Volumes/EPD-6.1/EPD.mpkg -tgt /
mv ~/.bash_profile.bak ~/.bash_profile
umount /Volumes/EPD-6.1

cd /usr/bin
sudo mv python python_default
sudo mv python-config python-config_default
sudo ln -s /Library/Frameworks/Python.framework/Versions/Current/bin/python
sudo ln -s /Library/Frameworks/Python.framework/Versions/Current/bin/python-config

cd ~/src/gsl-1.14
./configure CFLAGS="-arch i386" LDFLAGS="-arch i386"
make
sudo make install

cd ~/src/bct-cpp
rm Makefile
curl -o Makefile http://156.56.29.176/Makefile
curl -o mak http://156.56.29.176/mak
chmod +x mak
sudo ./mak
