#! /usr/bin/env bash

SUFFIX=carry2_maxCarry3

RUN_DIR=../build/Development/run_${SUFFIX}

MakeRecent ${RUN_DIR}

CalcComplexity -C P Recent ${RUN_DIR}
plot n -v P -o ${SUFFIX}_Cp.eps ${RUN_DIR}

CalcMetrics -v swi_p_wd_npl_10_wp ${RUN_DIR}
plot g -g D,R_10_wp -v cc_p_wd -o ${SUFFIX}_cc_p_wd.eps ${RUN_DIR}
plot g -g D,R_10_wp -v npl_p_wd -o ${SUFFIX}_npl_p_wd.eps ${RUN_DIR}
plot g -v swi_p_wd_npl_10_wp -o ${SUFFIX}_swi_p_wd_npl_10_wp.eps ${RUN_DIR}

plot s -v agents -o ${SUFFIX}_pop.eps ${RUN_DIR}

